# Generated by Django 3.0.3 on 2020-03-02 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('species', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=50)),
                ('purchasedate', models.DateField()),
                ('purchaseloc', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('growthstage', models.CharField(choices=[('SPROUT', 'Sprout'), ('SEEDLING', 'Seedling'), ('JUVINILLE', 'Juvinille'), ('MATURE', 'Mature'), ('ESTABLISHED', 'Established')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WATERING', 'Watering'), ('FERTILIZING', 'Fertilizing'), ('PESTCONTROL', 'Pest Control')], max_length=20)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('interval', models.IntegerField()),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='plantabase.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plantabase.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='plantabase.Plant')),
            ],
        ),
    ]
