# Generated by Django 3.0.3 on 2020-03-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantabase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
